### ISSUE TITLE
Get submatrix from a DistanceMatrix

### ISSUE THREAD

**Issue by maurobedoya** [franciscoadasme/hclust#1]
After obtaining the clusters with the `HClust.cluster` method, an array of arrays is returned, representing the elements and the clusters with each element.
From this output, a new method to obtain a new distance matrix from each cluster would be useful.

**Comment by maurobedoya** [comment]
Additionally, after obtaining the new distance matrix that has already been calculated, a new method would be useful to obtain the `centroid` element of each cluster.

**Comment by franciscoadasme** [comment]
I'll create another issue for the second request, and rename this issue to better describe the feature.
